Fix `__hash__` type annotation
Annotating the type of this as `None` like is currently done causes mypy to generate an error, like this:

```
hash.py:2: error: Incompatible types in assignment (expression has type "None", base class "object" defined the type as "Callable[[object], int]")
```

https://github.com/python/mypy/issues/4266

Annotating this as `ClassVar[None]` seems to work.  My other attempt of annotating as e.g. `Optional[Callable]` doesn't